name: Release Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Description
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          NEW_BODY="Updated description: \n\n${{ github.event.pull_request.body }}\n\n_Auto-updated by GitHub Action_"

          curl -X PATCH -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/$REPO/pulls/$PR_NUMBER \
               -d "{\"body\":\"$NEW_BODY\"}"
