name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: |
          cat <<'EOF' >.npmrc
          # Auth with the set token.
          //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
          registry=https://registry.npmjs.org/
          always-auth=true

          # Allow versioned (non-`workspace:`) references between packages in
          # the workspace. This lets Nx verify the lockfile after version bumps
          # and before actually publishing the packages to the registry, since
          # the bumped versions won't be found in the registry yet.
          link-workspace-packages=true
          EOF

      - name: Update Release PR or Release
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          MAIN_BRANCH_NAME: ${{ github.event.repository.default_branch }}
          COMMIT_BEFORE: ${{ github.event.before }}
          RELEASE_BRANCH_NAME: release
          NX_VERBOSE_LOGGING: true
        run: pnpm tsx ./release.ts
