name: Release Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  update-pr-description:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      REPO: ${{ github.repository }}
      NEW_BODY: '!!!'

    steps:
      - name: Debug
        run: |
          echo GH_TOKEN: ${#GH_TOKEN} characters
          echo curl -X PATCH -H "Authorization: token <GH_TOKEN>" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/$REPO/pulls/$PR_NUMBER \
               --fail \
               -d "{\"body\":\"$NEW_BODY\"}"

      - name: Update PR Description
        run: |
          curl -X PATCH -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/$REPO/pulls/$PR_NUMBER \
               --fail \
               -d "{\"body\":\"$NEW_BODY\"}"
